### ISSUE TITLE
【フロントエンド／バックエンド】Firestore／Realtime Databaseの構造を定義する

### ISSUE THREAD

**Issue by Futaba-Kosuke** [Futaba-Kosuke/shogi-camera-server#7]
### 概要
DBの構造を定義する。
FirestoreとRealtime Databaseの両方を使用するものとする。

### 注意点
DBの構造については全体に周知するため、Wikiに記載すること。

### 終了条件
- DBの構造が定義されている

**Comment by FukeKazki** [comment]
I think ... 🤔 
![紫陽花-40 2](https://user-images.githubusercontent.com/40536586/144276696-da139405-a1be-4f57-8180-068dd2a08189.jpg)
